export const ROUTES = {
  home: '/',
  explore: '/explore',
  community: '/community',
  forSeniors: '/for-seniors',
  forYouth: '/for-youth',
  forNgo: '/for-ngo',
  about: '/about',
  mission: '/mission',
  careers: '/careers',
  contact: '/contact',
  help: '/help',
  communityGuidelines: '/community-guidelines',
  safety: '/safety',
  reportIssue: '/report-issue',
  feedback: '/feedback',
  support: '/support',
  privacy: '/privacy-policy',
  terms: '/terms',
  cookies: '/cookie-policy',
  teams: '/teams',
  salesRefunds: '/sales-and-refunds',
  legal: '/legal',
  sitemap: '/sitemap',
};

export const SOCIAL_LINKS = [
  { label: 'Facebook', href: 'https://facebook.com/agewellus' },
  { label: 'Twitter', href: 'https://twitter.com/agewellus' },
  { label: 'Discord', href: 'https://discord.gg/agewellus' },
  { label: 'Telegram', href: 'https://t.me/agewellus' },
  { label: 'Instagram', href: 'https://www.instagram.com/agewell.us/' },
  { label: 'Threads', href: 'https://threads.net/@agewellus' },
];
